// Optional suggestions only. Nothing is selected or treated as a hard constraint by default.
export const profileOptions = {
  role: [
    "백엔드 개발자",
    "프런트엔드 개발자",
    "풀스택 개발자",
    "웹 개발자",
    "앱 개발자",
    "데이터 엔지니어",
    "데이터 분석가",
    "AI·ML 엔지니어",
    "DevOps·인프라",
    "QA 엔지니어",
    "보안 엔지니어",
    "게임 개발자",
  ],
  skills: [
    "Java",
    "Spring Boot",
    "Kotlin",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue",
    "Node.js",
    "Python",
    "Django",
    "FastAPI",
    "C#",
    ".NET",
    "C++",
    "Go",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "Redis",
    "MongoDB",
    "AWS",
    "Docker",
    "Kubernetes",
    "Git",
    "Linux",
  ],
  region: [
    "서울",
    "경기",
    "인천",
    "부산",
    "대구",
    "대전",
    "광주",
    "울산",
    "세종",
    "강원",
    "충북",
    "충남",
    "전북",
    "전남",
    "경북",
    "경남",
    "제주",
    "전국",
    "원격근무",
  ],
  exclusions: [
    "제외: 파견",
    "제외: 상주근무",
    "제외: 계약직",
    "제외: 교대근무",
    "제외: 야간근무",
    "확인: SI/SM",
    "확인: 포괄임금제",
    "확인: 수습기간·급여",
    "확인: 야근·주말근무",
    "확인: 출장 빈도",
    "확인: 연봉 범위",
    "확인: 재택·유연근무",
    "확인: 실제 담당 업무",
    "확인: 사용 기술",
  ],
};
